# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lexicalCast <- function(v) {
    .Call(`_strsplit_fix_num_lexicalCast`, v)
}

strsplit_fix_num <- function(v, N) {
    .Call(`_strsplit_fix_num_strsplit_fix_num`, v, N)
}

